name: aaic_walltime_prediction_model
channels:
  - conda-forge
dependencies:
  - python=3.6.5
  - pip
  - pip:
    - mlflow==1.17.0
    - matplotlib==3.3.4
    - pandas==1.1.5
    - scikit-learn==0.24.2
    - xgboost==1.4.2
